# Generated by Django 2.0.7 on 2018-07-22 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170329_0055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpeoplerelationship',
            name='page',
        ),
        migrations.RemoveField(
            model_name='blogpeoplerelationship',
            name='people',
        ),
        migrations.DeleteModel(
            name='BlogPeopleRelationship',
        ),
    ]
