# Generated by Django 2.0.7 on 2018-07-22 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        # ('blog', '0004_auto_20180722_0602'),
        ('base', '0005_breed_horse'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FooterText',
        ),
        migrations.RemoveField(
            model_name='people',
            name='image',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='featured_section_1',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='featured_section_1_title',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='featured_section_2',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='featured_section_2_title',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='featured_section_3',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='featured_section_3_title',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='promo_image',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='promo_text',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='promo_title',
        ),
        migrations.DeleteModel(
            name='People',
        ),
    ]
