# Generated by Django 2.0.7 on 2018-07-22 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20180722_0602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horse',
            name='breed',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='base.Breed'),
        ),
    ]
