# Generated by Django 2.0.7 on 2018-07-22 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_horse_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horse',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
