# Generated by Django 2.0.7 on 2018-07-22 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_auto_20180722_2235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horse',
            name='description',
        ),
    ]
