# Generated by Django 2.0.7 on 2018-07-22 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_auto_20180722_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='horse',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='horse',
            name='real_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
