# Generated by Django 2.0.7 on 2018-07-24 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_horse_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horse',
            name='breed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailcore.Collection'),
        ),
    ]
