# Generated by Django 2.0.7 on 2018-07-24 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_auto_20180724_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horse',
            name='documents',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtaildocs.Document'),
        ),
    ]
