# Generated by Django 2.0.7 on 2018-07-24 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0007_merge'),
        ('base', '0018_auto_20180724_0113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horse',
            name='documents',
        ),
        migrations.AddField(
            model_name='horse',
            name='documents',
            field=models.ManyToManyField(blank=True, null=True, to='wagtaildocs.Document'),
        ),
    ]
