# Generated by Django 2.0.7 on 2018-07-24 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0020_add-verbose-name'),
        ('base', '0019_auto_20180724_0121'),
    ]

    operations = [
        migrations.AddField(
            model_name='horse',
            name='images',
            field=models.ManyToManyField(blank=True, null=True, to='wagtailimages.Image'),
        ),
    ]
