# Generated by Django 2.0.7 on 2018-07-29 00:32

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('base', '0020_horse_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horse',
            name='documents',
        ),
        migrations.AddField(
            model_name='horse',
            name='collection',
            field=models.ForeignKey(blank=True, help_text='Landscape mode only; horizontal width between 1000px and 3000px.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Collection'),
        ),
        migrations.AlterField(
            model_name='horse',
            name='description',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
    ]
