# Generated by Django 2.0.7 on 2018-07-29 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_auto_20180729_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horse',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
