# Generated by Django 2.0.7 on 2018-07-29 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_auto_20180729_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horse',
            name='collection',
            field=models.ForeignKey(blank=True, help_text='Select the collection for this horse.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='horse_images', to='wagtailcore.Collection'),
        ),
    ]
