# Generated by Django 2.0.7 on 2018-07-29 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_auto_20180729_0041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horse',
            name='images',
        ),
        migrations.AlterField(
            model_name='horse',
            name='breed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.Breed'),
        ),
    ]
