# Generated by Django 2.0.7 on 2018-07-30 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_auto_20180730_0453'),
    ]

    operations = [
        migrations.AddField(
            model_name='horse',
            name='stud_service',
            field=models.NullBooleanField(),
        ),
    ]
