# Generated by Django 2.0.7 on 2018-07-30 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_auto_20180730_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horse',
            name='stud_service',
            field=models.NullBooleanField(help_text='Check if horse is only for Stud Use'),
        ),
    ]
