# Generated by Django 2.0.7 on 2018-07-30 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_horse_in_foal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horse',
            name='in_foal',
        ),
        migrations.AddField(
            model_name='horse',
            name='price',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='horse',
            name='stud_fee',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='horse',
            name='description',
            field=models.TextField(blank=True, help_text='Add in foal information', null=True),
        ),
    ]
