# Generated by Django 2.0.7 on 2018-07-31 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_auto_20180730_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horse',
            name='price',
            field=models.TextField(blank=True, help_text='Do not enter $ sign', null=True),
        ),
        migrations.AlterField(
            model_name='horse',
            name='stud_fee',
            field=models.TextField(blank=True, help_text='Do not enter $ sign', null=True),
        ),
    ]
