# Generated by Django 2.0.7 on 2018-08-08 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_socialmediasettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmediasettings',
            name='facebook',
            field=models.URLField(blank=True, help_text='Your Facebook page URL'),
        ),
        migrations.AlterField(
            model_name='socialmediasettings',
            name='instagram',
            field=models.CharField(blank=True, help_text='Your Instagram username, without the @', max_length=255),
        ),
        migrations.AlterField(
            model_name='socialmediasettings',
            name='trip_advisor',
            field=models.URLField(blank=True, help_text='Your Trip Advisor page URL'),
        ),
        migrations.AlterField(
            model_name='socialmediasettings',
            name='youtube',
            field=models.URLField(blank=True, help_text='Your YouTube channel or user account URL'),
        ),
    ]
