# Generated by Django 2.0.7 on 2018-08-08 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('base', '0033_auto_20180808_0251'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copyright', models.TextField(blank=True, null=True)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='socialmediasettings',
            name='trip_advisor',
        ),
        migrations.AddField(
            model_name='socialmediasettings',
            name='twitter',
            field=models.URLField(blank=True, help_text='Your Twitter page URL'),
        ),
        migrations.AlterField(
            model_name='socialmediasettings',
            name='instagram',
            field=models.URLField(blank=True, help_text='Your Instagram Page URL', max_length=255),
        ),
    ]
